# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Power < Formula
  desc ""
  homepage ""
  version "0.0.1"
  bottle :unneeded
  depends_on :linux

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/steveh/power/releases/download/0.0.1/power_0.0.1_Linux_x86_64.tar.gz"
    sha256 "c8b802fdcf7748b43c48d261fd386de35cda59ea8a48aa4cf7ec03e8729ca572"
  end

  def install
    bin.install "power"
  end
end
