# This file was generated by GoReleaser. DO NOT EDIT.
cask "backup" do
  require "utils/github"
  require "json"
  require "net/http"
  require "uri"

  module GitHubHelper
    def self.token
      github_token = Homebrew::EnvConfig.github_api_token
      github_token = netrc_token if github_token.nil? || github_token.empty?
      github_token ||= GitHub::API.credentials
      raise "Failed to retrieve github api token" if github_token.nil? || github_token.empty?
      github_token
    end

    def self.netrc_token
      netrc_path = File.expand_path("~/.netrc")
      return nil unless File.exist?(netrc_path)

      begin
        current_machine = nil
        File.foreach(netrc_path) do |line|
          # Normalize line endings and surrounding whitespace
          line = line.to_s.strip
          next if line.empty? || line.start_with?("#")

          # Split on any whitespace
          tokens = line.split(/\s+/)
          next if tokens.empty?

          if tokens[0] == "machine" && tokens[1]
            current_machine = tokens[1]
          elsif current_machine == "github.com"
            # Handle both "password TOKEN" on its own line and
            # "machine github.com login user password TOKEN" formats.
            password_index = tokens.index("password")
            return tokens[password_index + 1] if password_index && tokens[password_index + 1]
          end
        end
      rescue
        # If netrc parsing fails, fall back to other mechanisms
      end

      nil
    end

    def self.release_asset_url(tag, name)
      resp = Net::HTTP.get(
        URI.parse("https://api.github.com/repos/steveh/backup/releases/tags/#{tag}"),
        {
          "Accept" => "application/vnd.github+json",
          "Authorization" => "Bearer #{token}",
          "X-GitHub-Api-Version" => "2022-11-28"
        }
      )

      release = JSON.parse(resp)
      asset = release["assets"].find { |asset| asset["name"] == name }
      asset["url"]
    end
  end

  name "backup"
  desc "Backup CLI"
  homepage "https://github.com/steveh/backup"
  version "0.3.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backup"

  on_macos do
    on_intel do
      url "#{GitHubHelper.release_asset_url("#{version}", "backup_#{version}_darwin_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "beceb02e9c992f7d55a9307e0f2b01a3fddbe148e5b672e49a7ae8626f9e9cf2"
    end
    on_arm do
      url "#{GitHubHelper.release_asset_url("#{version}", "backup_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "40f4300c5b7b7ddbce4710380be2d0c664f316866404cb3dab71f7f13851f4b6"
    end
  end

  on_linux do
    on_intel do
      url "#{GitHubHelper.release_asset_url("#{version}", "backup_#{version}_linux_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "820a7fbfd9e9702e19c135cdcf09f5a081be064aec4c1aebc31e4fd7954c03f8"
    end
    on_arm do
      url "#{GitHubHelper.release_asset_url("#{version}", "backup_#{version}_linux_aarch64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "2fa69dc8e633b5a10f66b80d6b9cb3a1f4c8f712cac6e055a6297854ab71c4c8"
    end
  end

  # No zap stanza required
end
