# This file was generated by GoReleaser. DO NOT EDIT.
cask "lilregie-cli" do
  require "utils/github"
  require "json"
  require "net/http"
  require "uri"

  module GitHubHelper
    def self.token
      github_token = Homebrew::EnvConfig.github_api_token
      github_token = netrc_token if github_token.nil? || github_token.empty?
      github_token ||= GitHub::API.credentials
      raise "Failed to retrieve github api token" if github_token.nil? || github_token.empty?
      github_token
    end

    def self.netrc_token
      netrc_path = File.expand_path("~/.netrc")
      return nil unless File.exist?(netrc_path)

      begin
        current_machine = nil
        File.foreach(netrc_path) do |line|
          # Normalize line endings and surrounding whitespace
          line = line.to_s.strip
          next if line.empty? || line.start_with?("#")

          # Split on any whitespace
          tokens = line.split(/\s+/)
          next if tokens.empty?

          if tokens[0] == "machine" && tokens[1]
            current_machine = tokens[1]
          elsif current_machine == "github.com"
            # Handle both "password TOKEN" on its own line and
            # "machine github.com login user password TOKEN" formats.
            password_index = tokens.index("password")
            return tokens[password_index + 1] if password_index && tokens[password_index + 1]
          end
        end
      rescue
        # If netrc parsing fails, fall back to other mechanisms
      end

      nil
    end

    def self.release_asset_url(tag, name)
      resp = Net::HTTP.get(
        URI.parse("https://api.github.com/repos/lilregie/cli/releases/tags/#{tag}"),
        {
          "Accept" => "application/vnd.github+json",
          "Authorization" => "Bearer #{token}",
          "X-GitHub-Api-Version" => "2022-11-28"
        }
      )

      release = JSON.parse(resp)
      asset = release["assets"].find { |asset| asset["name"] == name }
      asset["url"]
    end
  end

  name "lilregie-cli"
  desc "Lil Regie CLI"
  homepage "https://github.com/lilregie/cli"
  version "0.13.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lilregie"

  on_macos do
    on_intel do
      url "#{GitHubHelper.release_asset_url("#{version}", "lilregie-cli_#{version}_darwin_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "e00c158e57a7182d860aaec42bbd8995154aaae2740da58b3b605e052cca2397"
    end
    on_arm do
      url "#{GitHubHelper.release_asset_url("#{version}", "lilregie-cli_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "8cde22b4ea8ee01b8c98e07911811e59880cf19d6933eb1be84a55906c26d840"
    end
  end

  on_linux do
    on_intel do
      url "#{GitHubHelper.release_asset_url("#{version}", "lilregie-cli_#{version}_linux_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "ce9af803dfc89a3e6f94c05b366b6478476323bde2f221ab442e679aa9533ede"
    end
    on_arm do
      url "#{GitHubHelper.release_asset_url("#{version}", "lilregie-cli_#{version}_linux_aarch64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "870c401b341405b44b6d3b1222d98693126c6db5858bb8f087c64726b530dea2"
    end
  end

  # No zap stanza required
end
