# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private"
class Neuter < Formula
  desc "Social neuterer"
  homepage "https://github.com/kotiri/neuter"
  version "0.0.3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/steveh/neuter/releases/download/0.0.3/neuter_0.0.3_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "db05454e619ff630ad3b1cf01666128d10880a42eee8957495784cdd1a0ecc3f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/steveh/neuter/releases/download/0.0.3/neuter_0.0.3_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "5b03b943b10462d64610d768fc72e15ea2aa9caa69268cd12d8b90b25f346d35"
  end

  def install
    bin.install "neuter"
  end
end
