# This file was generated by GoReleaser. DO NOT EDIT.
cask "power" do
  require "utils/github"
  require "json"
  require "net/http"
  require "uri"

  module GitHubHelper
    def self.token
      github_token = Homebrew::EnvConfig.github_api_token
      github_token = netrc_token if github_token.nil? || github_token.empty?
      github_token ||= GitHub::API.credentials
      raise "Failed to retrieve github api token" if github_token.nil? || github_token.empty?
      github_token
    end

    def self.netrc_token
      netrc_path = File.expand_path("~/.netrc")
      return nil unless File.exist?(netrc_path)

      begin
        current_machine = nil
        File.foreach(netrc_path) do |line|
          # Normalize line endings and surrounding whitespace
          line = line.to_s.strip
          next if line.empty? || line.start_with?("#")

          # Split on any whitespace
          tokens = line.split(/\s+/)
          next if tokens.empty?

          if tokens[0] == "machine" && tokens[1]
            current_machine = tokens[1]
          elsif current_machine == "github.com"
            # Handle both "password TOKEN" on its own line and
            # "machine github.com login user password TOKEN" formats.
            password_index = tokens.index("password")
            return tokens[password_index + 1] if password_index && tokens[password_index + 1]
          end
        end
      rescue
        # If netrc parsing fails, fall back to other mechanisms
      end

      nil
    end

    def self.release_asset_url(tag, name)
      resp = Net::HTTP.get(
        URI.parse("https://api.github.com/repos/steveh/power/releases/tags/#{tag}"),
        {
          "Accept" => "application/vnd.github+json",
          "Authorization" => "Bearer #{token}",
          "X-GitHub-Api-Version" => "2022-11-28"
        }
      )

      release = JSON.parse(resp)
      asset = release["assets"].find { |asset| asset["name"] == name }
      asset["url"]
    end
  end

  name "power"
  desc "Lil Regie CLI"
  homepage "https://github.com/steveh/power"
  version "1.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lilregie"

  on_macos do
    on_intel do
      url "#{GitHubHelper.release_asset_url("#{version}", "power_#{version}_darwin_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "4f590f850b9110fc94a2ff3f401b492cf2ffb3a3cb719cce123ef365e977f286"
    end
    on_arm do
      url "#{GitHubHelper.release_asset_url("#{version}", "power_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "0fc4c9edc853ac5902a42a428258b8f50b063efb87fbecbf169a33bd17530d7b"
    end
  end

  on_linux do
    on_intel do
      url "#{GitHubHelper.release_asset_url("#{version}", "power_#{version}_linux_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "03304a838208a36e1b0114e1b6bfa58e9fc7aa15b38a78df766d7af0d8a23c54"
    end
    on_arm do
      url "#{GitHubHelper.release_asset_url("#{version}", "power_#{version}_linux_aarch64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "0e94ab7faca4efa8ed065bf1af3a0103fd2caad5beb3ecee898341cee3ff5508"
    end
  end

  # No zap stanza required
end
