# This file was generated by GoReleaser. DO NOT EDIT.
cask "power" do
  require "utils/github"
  require "json"
  require "net/http"
  require "uri"

  module GitHubHelper
    def self.token
      github_token = Homebrew::EnvConfig.github_api_token
      github_token = netrc_token if github_token.nil? || github_token.empty?
      github_token ||= GitHub::API.credentials
      raise "Failed to retrieve github api token" if github_token.nil? || github_token.empty?
      github_token
    end

    def self.netrc_token
      netrc_path = File.expand_path("~/.netrc")
      return nil unless File.exist?(netrc_path)

      begin
        current_machine = nil
        File.foreach(netrc_path) do |line|
          # Normalize line endings and surrounding whitespace
          line = line.to_s.strip
          next if line.empty? || line.start_with?("#")

          # Split on any whitespace
          tokens = line.split(/\s+/)
          next if tokens.empty?

          if tokens[0] == "machine" && tokens[1]
            current_machine = tokens[1]
          elsif current_machine == "github.com"
            # Handle both "password TOKEN" on its own line and
            # "machine github.com login user password TOKEN" formats.
            password_index = tokens.index("password")
            return tokens[password_index + 1] if password_index && tokens[password_index + 1]
          end
        end
      rescue
        # If netrc parsing fails, fall back to other mechanisms
      end

      nil
    end

    def self.release_asset_url(tag, name)
      resp = Net::HTTP.get(
        URI.parse("https://api.github.com/repos/steveh/power/releases/tags/#{tag}"),
        {
          "Accept" => "application/vnd.github+json",
          "Authorization" => "Bearer #{token}",
          "X-GitHub-Api-Version" => "2022-11-28"
        }
      )

      release = JSON.parse(resp)
      asset = release["assets"].find { |asset| asset["name"] == name }
      asset["url"]
    end
  end

  version "1.5.12"

  on_macos do
    on_intel do
      sha256 "5093340a732eb43053aefe81e373ea523ca05c6f00a986674a26c6aad05a0ebc"
      url "#{GitHubHelper.release_asset_url("#{version}", "power_#{version}_darwin_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "20d3ef7ff7c4c77b8e8018a3f2a0c5e8b09ce5425e9796ee76ba62dd06421918"
      url "#{GitHubHelper.release_asset_url("#{version}", "power_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  on_linux do
    on_intel do
      sha256 "c298dff8c7473d46fa16b932b91d7c18e958f52bdf926c100a5dd87876dc14e5"
      url "#{GitHubHelper.release_asset_url("#{version}", "power_#{version}_linux_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "01bfe7e80fc48246c5ce222aa50d09d19a725b1823e21a8cb51b71068ebb34ae"
      url "#{GitHubHelper.release_asset_url("#{version}", "power_#{version}_linux_aarch64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  name "power"
  desc "Power CLI"
  homepage "https://github.com/steveh/power"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "power"

  # No zap stanza required

end
