# This file was generated by GoReleaser. DO NOT EDIT.
cask "sens" do
  require "utils/github"
  require "json"
  require "net/http"
  require "uri"

  module GitHubHelper
    def self.token
      github_token = Homebrew::EnvConfig.github_api_token
      github_token = netrc_token if github_token.nil? || github_token.empty?
      github_token ||= GitHub::API.credentials
      raise "Failed to retrieve github api token" if github_token.nil? || github_token.empty?
      github_token
    end

    def self.netrc_token
      netrc_path = File.expand_path("~/.netrc")
      return nil unless File.exist?(netrc_path)

      begin
        current_machine = nil
        File.foreach(netrc_path) do |line|
          # Normalize line endings and surrounding whitespace
          line = line.to_s.strip
          next if line.empty? || line.start_with?("#")

          # Split on any whitespace
          tokens = line.split(/\s+/)
          next if tokens.empty?

          if tokens[0] == "machine" && tokens[1]
            current_machine = tokens[1]
          elsif current_machine == "github.com"
            # Handle both "password TOKEN" on its own line and
            # "machine github.com login user password TOKEN" formats.
            password_index = tokens.index("password")
            return tokens[password_index + 1] if password_index && tokens[password_index + 1]
          end
        end
      rescue
        # If netrc parsing fails, fall back to other mechanisms
      end

      nil
    end

    def self.release_asset_url(tag, name)
      resp = Net::HTTP.get(
        URI.parse("https://api.github.com/repos/steveh/sens/releases/tags/#{tag}"),
        {
          "Accept" => "application/vnd.github+json",
          "Authorization" => "Bearer #{token}",
          "X-GitHub-Api-Version" => "2022-11-28"
        }
      )

      release = JSON.parse(resp)
      asset = release["assets"].find { |asset| asset["name"] == name }
      asset["url"]
    end
  end

  version "0.1.39"

  on_macos do
    on_intel do
      sha256 "180ab2efd992aae9b7e802279ce942ac4d6fb7527601324411b0eeea9e89e1c7"
      url "#{GitHubHelper.release_asset_url("#{version}", "sens_#{version}_darwin_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "301189fe5c2d706fb3d4c766b41d7e539588a93ca32a1a6ca0f04d3f920399ad"
      url "#{GitHubHelper.release_asset_url("#{version}", "sens_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  on_linux do
    on_intel do
      sha256 "2ea2df4e5ecfd053ebdd773851d7831d4ce764d9d005b672609b53e866212db5"
      url "#{GitHubHelper.release_asset_url("#{version}", "sens_#{version}_linux_x86_64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "f6be31ce9bfd611db380ebe0e2c0209ee944ee89065997553e657737c1e946bf"
      url "#{GitHubHelper.release_asset_url("#{version}", "sens_#{version}_linux_aarch64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  name "sens"
  desc "Sensors"
  homepage "https://github.com/steveh/sens"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sens"

  # No zap stanza required

end
