# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backup < Formula
  desc "Backups"
  homepage "https://github.com/kotiri/backup"
  version "0.0.3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/steveh/backup/releases/download/0.0.3/backup_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "057eee6cb54722b8f0f885316400cc26175fb91e9a377d3f3c165afce69b90e1"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/steveh/backup/releases/download/0.0.3/backup_0.0.3_Linux_x86_64.tar.gz"
    sha256 "04aee30d404f1d36093424ffcca2fd4867456e800198fccaa7d98c1800c5bde3"
  end

  def install
    bin.install "backup"
  end
end
