# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private"
class Backup < Formula
  desc "Backups"
  homepage "https://github.com/steveh/backup"
  version "0.0.5"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveh/backup/releases/download/0.0.5/backup_0.0.5_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f5ea97a291b6f4f5556dd508ce424fd59eccdc76e0b318e478e883d224dddbe5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/steveh/backup/releases/download/0.0.5/backup_0.0.5_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "02a940b913b1ad177ab038c4d1455ce0ce89d10824ccd31c9e71744bd8cc13a0"
    end
  end

  def install
    bin.install "backup"
  end
end
