# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private"
class Backup < Formula
  desc "Backups"
  homepage "https://github.com/kotiri/backup"
  version "0.0.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/steveh/backup/releases/download/0.0.4/backup_0.0.4_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "7d1382b6b3466681f27cbdfef5d2a8002b60909f6f3bd77cb5da22e35c4366ea"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/steveh/backup/releases/download/0.0.4/backup_0.0.4_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "cc0e09286bc172fbbdd0e61d87af9736a408b2e2cac257bc7fb6df2442e6c545"
  end

  def install
    bin.install "backup"
  end
end
