# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private"
class LilregieCli < Formula
  desc "Lil Regie CLI"
  homepage "https://github.com/lilregie/cli"
  version "0.8.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lilregie/cli/releases/download/0.8.5/lilregie-cli_0.8.5_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c28ec172b461b63197477c8849c6f5b0384117ae00899b9c9a1671dae8110cb0"

      def install
        bin.install "lilregie"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lilregie/cli/releases/download/0.8.5/lilregie-cli_0.8.5_darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "530b60d361b2819f6904f1924b661e6b49aa1c575c0b05851127af2ccabbea86"

      def install
        bin.install "lilregie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lilregie/cli/releases/download/0.8.5/lilregie-cli_0.8.5_linux_aarch64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "09e5b0ae44ed4a2d79ec8169879a8923ca5c609ec2c24bf57e4a401a6be21f1c"

      def install
        bin.install "lilregie"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lilregie/cli/releases/download/0.8.5/lilregie-cli_0.8.5_linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "573d95079f65948a4f40326cf71acdc76b5033b6f49b7f606fe557c7d5977ff1"

      def install
        bin.install "lilregie"
      end
    end
  end
end
