# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private"
class Neuter < Formula
  desc "Social neuterer"
  homepage "https://github.com/kotiri/neuter"
  version "0.0.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/steveh/neuter/releases/download/0.0.4/neuter_0.0.4_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "9814c510c10b1e474d8eae00918df72b17674c10c4e4c73d90eaaaf3d844d8c7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/steveh/neuter/releases/download/0.0.4/neuter_0.0.4_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "234e7d2738755c33e752d8b448dff61d4bb8d221453b28ef1e5554d87848786b"
  end

  def install
    bin.install "neuter"
  end
end
