# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neuter < Formula
  desc "Social neuterer"
  homepage "https://github.com/kotiri/neuter"
  version "0.0.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/steveh/neuter/releases/download/0.0.2/neuter_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "fb4b6ee6d0ee093f4e8817672c2ab8bec9361272d8fd737f5fab20fddc4afb92"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/steveh/neuter/releases/download/0.0.2/neuter_0.0.2_Linux_x86_64.tar.gz"
    sha256 "b17c210ffc6f1ea81dbf6200f894c8e807997723bd23321cc039fe12781911e9"
  end

  def install
    bin.install "neuter"
  end
end
