# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private"
class Power < Formula
  desc "Power management"
  homepage "https://github.com/steveh/power"
  version "1.3.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveh/power/releases/download/1.3.4/power_1.3.4_darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "41bf04dd842e6efaed9056a5f3667305a9c6741730e4a6a1676ef882b3fc2648"

      def install
        bin.install "power"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveh/power/releases/download/1.3.4/power_1.3.4_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "09df5ff18b16ca15045ddcfc3a24b5b3e3f5233b36c2e53319815dbcec5fcd29"

      def install
        bin.install "power"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steveh/power/releases/download/1.3.4/power_1.3.4_linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "e6e268cf3cdae079bb0d360d87719ca110b2f97756993cf7f83f1937d588b18f"

        def install
          bin.install "power"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steveh/power/releases/download/1.3.4/power_1.3.4_linux_aarch64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "0c9391baa6bdbf00d7fc8b5e4a2891c49d62180736dc2f551103b21c43398ae6"

        def install
          bin.install "power"
        end
      end
    end
  end
end
