# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private"
class Power < Formula
  desc "Power management"
  homepage "https://github.com/steveh/power"
  version "1.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveh/power/releases/download/1.3.3/power_1.3.3_darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "111b45bbb49b5b67429922562fcf4b8e02e34227492a5de9f79657b77d4734a0"

      def install
        bin.install "power"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveh/power/releases/download/1.3.3/power_1.3.3_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ae9c1a18267bb002b8fb0c3569cbd845df07c4b15ffb35a2eedaa20028b5be44"

      def install
        bin.install "power"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steveh/power/releases/download/1.3.3/power_1.3.3_linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "ad0b9ea7f1e69af9e683cd7a1c85214d335ba2eb3b63b8baad1cf7d88360f1ae"

        def install
          bin.install "power"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steveh/power/releases/download/1.3.3/power_1.3.3_linux_aarch64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "5f6f1a5cb9a1fccbf235bee3b7baf4cf41007790906bc3fc7a3b402501d49982"

        def install
          bin.install "power"
        end
      end
    end
  end
end
