# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private"
class Power < Formula
  desc "Power management"
  homepage "https://github.com/steveh/power"
  version "1.0.4"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/steveh/power/releases/download/1.0.4/power_1.0.4_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "751866cd29259dee8f35b5d4c3c22a466a74d5f39ce595589844f68e44f147ea"

      def install
        bin.install "power"
      end
    end
  end
end
