# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TelegrafExecZpoolStatus < Formula
  desc "Extract zpool status and output Influx line protocol"
  homepage "https://github.com/steveh/telegraf-exec-zpool-status"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveh/telegraf-exec-zpool-status/releases/download/1.0.1/telegraf-exec-zpool-status_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "9413c47e76ea86c4d76d6d8968f9c7caeb8e548ba51009c439be58d39adb2dc0"

      def install
        bin.install "telegraf-exec-zpool-status"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveh/telegraf-exec-zpool-status/releases/download/1.0.1/telegraf-exec-zpool-status_1.0.1_Darwin_arm64.tar.gz"
      sha256 "76f9a4f2ef77c3b5a079e342680dc07c5cd37a5aa138ba2c79d2be295d17c59a"

      def install
        bin.install "telegraf-exec-zpool-status"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/steveh/telegraf-exec-zpool-status/releases/download/1.0.1/telegraf-exec-zpool-status_1.0.1_Linux_x86_64.tar.gz"
      sha256 "8e36517fc82192efa97de7bfc4bdd7d3482c61da465cc2935553d59f53db5c64"

      def install
        bin.install "telegraf-exec-zpool-status"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveh/telegraf-exec-zpool-status/releases/download/1.0.1/telegraf-exec-zpool-status_1.0.1_Linux_arm64.tar.gz"
      sha256 "bee99fed6679947e881d60a4708c2dcc415c2da11bbbfb1fb28650939816f2ab"

      def install
        bin.install "telegraf-exec-zpool-status"
      end
    end
  end
end
