# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TelegrafExecStorcli < Formula
  desc "Extract Broadcom StorCLI and output Influx line protocol"
  homepage "https://github.com/steveh/telegraf-exec-storcli"
  version "1.0.0"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/steveh/telegraf-exec-storcli/releases/download/1.0.0/telegraf-exec-storcli_1.0.0_Linux_x86_64.tar.gz"
      sha256 "8f87401de91de376a0a3802b7fa4ccfdcf48a98f2abd8f8421b7c0091db73412"

      def install
        bin.install "telegraf-exec-storcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveh/telegraf-exec-storcli/releases/download/1.0.0/telegraf-exec-storcli_1.0.0_Linux_arm64.tar.gz"
      sha256 "1cdcc217f340fdf1f3e4eed162e341534278c849ed752d12e8e93c5db5f606f7"

      def install
        bin.install "telegraf-exec-storcli"
      end
    end
  end
end
