# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TelegrafExecNut < Formula
  desc "Extract Network UPS Tools and output Influx line protocol"
  homepage "https://github.com/steveh/telegraf-exec-nut"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/steveh/telegraf-exec-nut/releases/download/0.0.1/telegraf-exec-nut_0.0.1_Darwin_arm64.tar.gz"
      sha256 "895063d302ab6bddf70cc48edae51391ce673edbbe58c97c771f982493da1e8b"

      def install
        bin.install "telegraf-exec-nut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steveh/telegraf-exec-nut/releases/download/0.0.1/telegraf-exec-nut_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "cbfebf4c6490c9758aa35f1e9e8dcc7d2ce8c1d60569d243f0fb6ab9b50de526"

      def install
        bin.install "telegraf-exec-nut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/steveh/telegraf-exec-nut/releases/download/0.0.1/telegraf-exec-nut_0.0.1_Linux_x86_64.tar.gz"
      sha256 "3a2c10f92b0aac92e300e4e1b70e17db284b9ae6146680946155a3889f849c1e"

      def install
        bin.install "telegraf-exec-nut"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveh/telegraf-exec-nut/releases/download/0.0.1/telegraf-exec-nut_0.0.1_Linux_arm64.tar.gz"
      sha256 "201e71002df3d94b7b2d06329cdfade2f958b5c413b1e05af1324eb9d81574f3"

      def install
        bin.install "telegraf-exec-nut"
      end
    end
  end
end
