# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TelegrafExecFronius < Formula
  desc "Extract Fronius solar data and output Influx line protocol"
  homepage "https://github.com/steveh/telegraf-exec-fronius"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveh/telegraf-exec-fronius/releases/download/0.0.1/telegraf-exec-fronius_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "69bed66144f2ba4774d8d27778a1a89f2d1df330276ff8f0f3ab2cb553417ce5"

      def install
        bin.install "telegraf-exec-fronius"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveh/telegraf-exec-fronius/releases/download/0.0.1/telegraf-exec-fronius_0.0.1_Darwin_arm64.tar.gz"
      sha256 "0da8944fee3c57a8235238b929b496b7aa69403f7877e5945d33c1999df37720"

      def install
        bin.install "telegraf-exec-fronius"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveh/telegraf-exec-fronius/releases/download/0.0.1/telegraf-exec-fronius_0.0.1_Linux_arm64.tar.gz"
      sha256 "f04da495fb8102c1d28722d3da1402483113deab879e0b7af87ff4bd79caa01c"

      def install
        bin.install "telegraf-exec-fronius"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/steveh/telegraf-exec-fronius/releases/download/0.0.1/telegraf-exec-fronius_0.0.1_Linux_x86_64.tar.gz"
      sha256 "ee9fb514e2350e16d377a9fa0ee3a220a513606dfe5845465f06fa7233d54e0b"

      def install
        bin.install "telegraf-exec-fronius"
      end
    end
  end
end
