# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private"
class WebsliceCli < Formula
  desc "Webslice CLI"
  homepage "https://github.com/steveh/webslice-cli"
  version "0.0.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveh/webslice-cli/releases/download/0.0.3/webslice-cli_0.0.3_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c66c673392f4c6732a29bb3027617c2135a719a201d6f6e8bc298bbcaeb69180"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/steveh/webslice-cli/releases/download/0.0.3/webslice-cli_0.0.3_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "392c6fe618701953715a6790771c8ec12c8312ef24464ae0f158db32335ddc7b"
    end
  end

  def install
    bin.install "webslice"
  end
end
